//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegaProductionBDDEntities : DbContext
    {
        public MegaProductionBDDEntities()
            : base("name=MegaProductionBDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annonceur> Annonceur { get; set; }
        public virtual DbSet<Artiste> Artiste { get; set; }
        public virtual DbSet<Casting> Casting { get; set; }
        public virtual DbSet<ContenuEditorial> ContenuEditorial { get; set; }
        public virtual DbSet<Domaine> Domaine { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Metier> Metier { get; set; }
        public virtual DbSet<Offre> Offre { get; set; }
        public virtual DbSet<PartenaireDiffusion> PartenaireDiffusion { get; set; }
        public virtual DbSet<RoleEmploye> RoleEmploye { get; set; }
        public virtual DbSet<TypeContenuEditorial> TypeContenuEditorial { get; set; }
    }
}
